version: "3.8"

volumes:
  mongo_data:

services:
  server:
    build: .
    container_name: "cooking-blog-server"
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
      - ${QUEUE_HTTP_PORT}:${QUEUE_HTTP_PORT}
    volumes:
      - .:/app/server
      - ./.logs:/app/server/.logs
    links:
      - redis

  #   mongo-backup:
  #     build: ./mongo
  #     container_name: "cooking-blog-mongo-backup"
  #     environment:
  #       DATABASE: ${MONGODB_BAK_DATABASE}
  #       MONGO_URI: ${MONGOOSE_URL}
  #       CRON_SCHEDULE: ${MONGODB_BAK_SCHEDULE}
  #     volumes:
  #       - ./mongo/backup:/backup
  #     depends_on:
  #       - mongo

  redis:
    image: redis
    container_name: "cooking-blog-redis"
    environment:
      REDIS_QUEUE_PORT: ${REDIS_QUEUE_PORT}
    command: ["redis-server", "--bind", "redis", "--port", "$REDIS_QUEUE_PORT"]
    ports:
      - "${REDIS_QUEUE_PORT}:${REDIS_QUEUE_PORT}"
