version: "3.8"

networks:
  cooking-blog:
    name: "cooking-blog-network"
    external: true

services:
  server:
    build: .
    container_name: "cooking-blog-server"
    networks:
      - cooking-blog
    volumes:
      - .:/app/server
      - ./.logs:/app/server/.logs
    links:
      - redis

  redis:
    image: redis
    container_name: "cooking-blog-redis"
    networks:
      - cooking-blog
    environment:
      REDIS_QUEUE_PORT: ${REDIS_QUEUE_PORT}
    command: ["redis-server", "--bind", "redis", "--port", "$REDIS_QUEUE_PORT"]
