version: "3.8"

networks:
  cooking-blog:
    name: "cooking-blog-network"

volumes:
  mongo_data:

services:
  server:
    build: .
    container_name: "cooking-blog-server"
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
      - ${QUEUE_HTTP_PORT}:${QUEUE_HTTP_PORT}
    networks:
      - cooking-blog
    volumes:
      - ./src:/app/server/src
      - ./.logs:/app/server/.logs
    links:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: "cooking-blog-mongo"
    environment:
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  mongo-backup:
    build: ./mongo
    container_name: "cooking-blog-mongo-backup"
    environment:
      DATABASE: ${MONGODB_BAK_DATABASE}
      MONGO_URI: "mongodb://mongo:27017"
      CRON_SCHEDULE: ${MONGODB_BAK_SCHEDULE}
    volumes:
      - ./mongo/backup:/backup
    depends_on:
      - mongo

  redis:
    image: redis
    container_name: "cooking-blog-redis"
    environment:
      REDIS_QUEUE_PORT: ${REDIS_QUEUE_PORT}
    command: ["redis-server", "--bind", "redis", "--port", "$REDIS_QUEUE_PORT"]
    ports:
      - "${REDIS_QUEUE_PORT}:${REDIS_QUEUE_PORT}"
